version: '3'
services:
  db:
    container_name: db_users
    image: postgres:14.5
    networks:
      - codeverso
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - db_users:/var/lib/postgres
  app:
    container_name: ms-users
    image: ms-users
    networks:
      - codeverso
    build:
      context: .
    ports:
      - "8080:8080"
    expose:
      - '8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/users
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

networks:
  codeverso:
    driver: bridge

volumes:
  db_users: