version: '3'
services:
  codeverso:
    container_name: codeverso
    image: codeverso:latest
    restart: always
    build: .
    ports:
      - "8082:8080"
    links:
      - db
  db:
    container_name: db_users
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db_users:/var/lib/postgres

volumes:
  db_users: