name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database-name:
        - users
        database-password:
        - root
        database-user:
        - admin
        database-host:
        - 127.0.0.1
        database-port:
        - 5432
        
    services:
      db:
        image: postgres:14.5
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      app:
        container_name: ms-users
        image: ms-users
        networks:
          - codeverso
        build:
          context: .
        ports:
          - "8080:8080"
        expose:
          - '8080'
        depends_on:
          - db
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/users
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Run migrations
        run: mvn flyway:migrate -Dflyway.url=jdbc:postgresql://localhost:5432/users -Dflyway.user=admin -Dflyway.password=root

networks:
  codeverso:
    driver: bridge

volumes:
  db_users: