name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        database-name:
        - users
        database-password:
        - root
        database-user:
        - admin
        database-host:
        - 127.0.0.1
        database-port:
        - 5432
        
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Run migrations
        run: mvn flyway:migrate -Dflyway.url=jdbc:postgresql://localhost:5432/users -Dflyway.user=admin -Dflyway.password=root

      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn spring-boot:run

      - name: curl
        uses: wei/curl@v1
        with:
          args: -X GET http://localhost:8080/users
